import { dateKey } from './routines.js';
import { workoutForDate, snapshotWorkout } from './editor.js';
import { editorScreen } from './editor-view.js';
import { esc, iconFor } from './dom.js';
import { loadState, saveState, addSession, clearHistory, statistics, exportHistory } from './storage.js';
import { workoutSession, exerciseSession } from './models.js';
import { CountdownTimer, formatSeconds } from './timer.js';
import { requestReminderPermission, scheduleBrowserReminder } from './notifications.js';

let state=loadState(localStorage), view='home', active=null, timer;
const app=document.querySelector('#app'),tabs=document.querySelector('#tabs');
const today=new Date(), dayFmt=new Intl.DateTimeFormat('es-ES',{weekday:'long',day:'numeric',month:'long'});
const TABS=['home:Hoy','calendar:Semana','editor:Editor','history:Historial','settings:Ajustes'];
const config=()=>state.configuration;
const shiftDate=date=>new Date(date.getFullYear(),date.getMonth(),date.getDate()+1);
const monday=()=>{const date=shiftDate(today);date.setDate(date.getDate()-((today.getDay()+6)%7));return date;};
const weekDates=()=>Array.from({length:7},(_,i)=>{const date=monday();date.setDate(date.getDate()+i);return date;});
const plannedFor=date=>workoutForDate(config(),date);
const nextWorkout=()=>plannedFor(shiftDate(today));
const mobilityWorkout=()=>config().workouts.find(w=>w.type==='movilidad')||null;
const exerciseById=id=>config().exercises.find(e=>e.id===id)||null;
const weekProgress=()=>{const dates=weekDates().map(dateKey),done=new Set(state.sessions.filter(s=>s.completedAt&&dates.includes(s.date)).map(s=>s.date));return{done:done.size,total:config().schedule.filter(Boolean).length};};
const commit=configuration=>{state={...state,configuration};persist();render();};
const persist=()=>{saveState(localStorage,state);applyTheme();scheduleBrowserReminder(state.preferences,plannedFor(today));};
const completedToday=()=>state.sessions.some(s=>s.date===dateKey(today)&&s.completedAt);
const button=(text,action,secondary=false)=>`<button class="${secondary?'secondary':''}" data-action="${action}">${text}</button>`;
const mediaFor=(exercise,item)=>{if(item.showAnimation===false)return'';const source=exercise?.gifPath||exercise?.thumbnailPath;return source?`<img class="gif" src="${esc(source)}" alt="${esc(exercise.displayName)}">`:'<div class="media">GIF disponible tras importar el dataset</div>';};
const instructionsFor=exercise=>exercise?.instructions?.length?`<ul class="instructions">${exercise.instructions.map(line=>`<li>${esc(line)}</li>`).join('')}</ul>`:'';
function shell(content){app.innerHTML=content;view==='session'?tabs.setAttribute('hidden',''):tabs.removeAttribute('hidden');tabs.innerHTML=TABS.map(x=>{let[a,b]=x.split(':');return `<button class="${view===a?'selected':''}" data-view="${a}">${b}</button>`}).join('');document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;render();});document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>act(b.dataset.action));}
function home(){const workout=plannedFor(today),next=nextWorkout(),mobility=mobilityWorkout(),progress=weekProgress(),done=completedToday();shell(`<header><p class="eyebrow">HOY</p><h1>${dayFmt.format(today)}</h1></header>${workout?`<section class="hero"><span>${iconFor(workout.type)}</span><p class="eyebrow">${esc(workout.type.toUpperCase())}</p><h2>${esc(workout.name)}</h2><p>${workout.isActivity?esc(workout.description||'Actividad libre'):`${workout.exercises.length} ejercicios · ${workout.rounds} rondas`}</p>${done?'<div class="complete">✓ Entrenamiento completado</div>':button('Comenzar entrenamiento','start')}</section>`:`<section class="hero"><p class="eyebrow">DESCANSO</p><h2>Sin rutina para hoy</h2><p>Asigna una rutina a hoy desde el editor.</p>${button('Abrir editor','goto-editor')}</section>`}<section><p class="eyebrow">MOVILIDAD</p><h2>Mobility &amp; Stretching</h2><p>Sesión guiada de ${mobility?mobility.exercises.length:0} ejercicios.</p>${mobility?button('Iniciar movilidad','start-mobility',true):'<p class="hint">No hay rutina de movilidad en el catálogo.</p>'}</section><section><p class="eyebrow">PRÓXIMO ENTRENAMIENTO</p>${next?`<h2>${esc(next.name)}</h2><p>${iconFor(next.type)} Mañana · ${esc(next.type)}</p>`:'<p>Mañana no hay rutina asignada.</p>'}</section><section><p class="eyebrow">PROGRESO</p><h2>Esta semana <strong>${progress.done}/${progress.total}</strong></h2>${progress.total?`<div class="bar"><i style="width:${progress.done/progress.total*100}%"></i></div>`:'<p class="hint">No hay días planificados en el editor.</p>'}</section>`);}
function calendar(){const days=weekDates();shell(`<header><p class="eyebrow">CALENDARIO</p><h1>Esta semana</h1></header><section class="week">${days.map((date,i)=>{const workout=plannedFor(date),done=state.sessions.some(s=>s.date===dateKey(date)&&s.completedAt);return `<button data-day="${i}" class="day ${dateKey(date)===dateKey(today)?'today':''}"><b>${'LMXJVSD'[i]}</b><span>${workout?iconFor(workout.type):'—'}</span><small>${workout?esc(workout.name):'Descanso'}</small><em>${done?'✓':'○'}</em></button>`;}).join('')}</section><section><h2>Plan de hoy</h2><p>${esc(plannedFor(today)?.description||'Rutina guiada con descansos automáticos.')}</p>${plannedFor(today)?'':'<p class="hint">Hoy no hay rutina asignada.</p>'}</section>`);document.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>{const workout=plannedFor(days[+b.dataset.day]);alert(workout?`${workout.name}\n${workout.description||(workout.isActivity?'Actividad libre':`${workout.exercises.length} ejercicios · ${workout.rounds} rondas`)}`:'Día de descanso: no hay rutina asignada.');});}
function history(){const sessions=[...state.sessions].filter(s=>s.completedAt).sort((a,b)=>b.completedAt.localeCompare(a.completedAt));const stat=statistics(state.sessions,today);shell(`<header><p class="eyebrow">HISTORIAL</p><h1>Tu progreso</h1></header><section class="stats"><div><b>${stat.completed}</b><span>completados</span></div><div><b>${stat.week}</b><span>esta semana</span></div><div><b>${stat.streak}</b><span>días seguidos</span></div></section><section><h2>Sesiones</h2>${sessions.length?sessions.map(s=>`<button class="history" data-session="${s.id}"><span>${new Intl.DateTimeFormat('es-ES',{day:'numeric',month:'short'}).format(new Date(s.completedAt))}</span><b>${esc(s.name)}</b><em>✓</em></button>`).join(''):'<p>Aún no has completado entrenamientos.</p>'}</section>`);document.querySelectorAll('[data-session]').forEach(b=>b.onclick=()=>{let s=sessions.find(x=>x.id===b.dataset.session);alert(`${s.name}\nDuración: ${Math.round(s.durationSeconds/60)} min\nEjercicios completados: ${s.completedExercises.length}`);});}
function settings(){let p=state.preferences,c=config();shell(`<header><p class="eyebrow">AJUSTES</p><h1>Personaliza</h1></header><section><h2>Recordatorios</h2><label class="toggle">Activar <input id="reminder" type="checkbox" ${p.reminders.enabled?'checked':''}></label><label>Hora <input id="time" type="time" value="${p.reminders.time}"></label><small>En web, el recordatorio funciona mientras esta app permanece abierta.</small></section><section><h2>Entrenamiento</h2><label>Descanso entre ejercicios <input id="rest-ex" type="number" min="0" value="${p.restBetweenExercises}"> segundos</label><label>Descanso entre rondas <input id="rest-round" type="number" min="0" value="${p.restBetweenRounds}"> segundos</label><label>Estiramientos <input id="stretch" type="number" min="5" value="${p.stretchSeconds}"> segundos</label></section><section><h2>Rutina</h2><p>${c.workouts.length} rutinas y ${c.exercises.length} ejercicios, guardados en este dispositivo.</p>${button('Editar rutina','goto-editor',true)}</section><section><h2>Apariencia</h2><select id="theme"><option value="system">Sistema</option><option value="light">Claro</option><option value="dark">Oscuro</option></select></section><section><h2>Datos</h2>${button('Guardar ajustes','save-settings')}${button('Exportar historial','export',true)}${button('Borrar historial','clear',true)}${button('Acerca de / licencias','about',true)}</section>`);document.querySelector('#theme').value=p.theme;}
function sessionView(){let {workout,index,round,phase}=active,item=workout.exercises[index],exercise=item&&(item.exercise||exerciseById(item.exerciseId)),rest=phase==='rest',upcoming=workout.exercises[index]&&(workout.exercises[index].exercise||exerciseById(workout.exercises[index].exerciseId));shell(`<header><button class="back" data-action="exit">× Salir</button><p class="eyebrow">${rest?'DESCANSO':workout.isActivity?'ACTIVIDAD':`RONDA ${round} / ${workout.rounds}`}</p></header><section class="session">${rest?`<h1>Descanso</h1><div id="clock" class="clock">${formatSeconds(active.seconds)}</div><p>Siguiente: <b>${esc(upcoming?.displayName||'')}</b></p>${button('Omitir descanso','skip-rest',true)}`:workout.isActivity?`<span class="activity-icon">${iconFor(workout.type)}</span><h1>${esc(workout.name)}</h1><p>${esc(workout.description||'Actividad libre')}</p>${button('Marcar como completado','complete-activity')}`:!item?`<h1>Rutina vacía</h1><p>Esta rutina no tiene ejercicios. Añádelos desde el editor.</p>${button('Salir','exit')}`:`<h1>${esc(exercise?.displayName||item.exerciseId)}</h1>${mediaFor(exercise,item)}${item.showInstructions===false?'':instructionsFor(exercise)}<h2>${esc(item.repetitions||`${item.durationSeconds} segundos`)}</h2>${item.notes?`<p>${esc(item.notes)}</p>`:''}${item.durationSeconds?`<div id="clock" class="clock">${formatSeconds(active.seconds)}</div>${button(active.paused?'Reanudar':'Pausar',active.paused?'resume':'pause',true)}`:''}${button('✓ Completar','complete-exercise')}${button('Repetir ejercicio','repeat',true)}${button('Saltar ejercicio','skip',true)}`}</section>`);}
function render(){if(view==='home')home();else if(view==='calendar')calendar();else if(view==='editor')editorScreen({shell,getConfig:config,commit,render});else if(view==='history')history();else if(view==='settings')settings();else sessionView();}
function begin(workout=plannedFor(today)){if(!workout)return;const snapshot=snapshotWorkout(config(),workout);active={workout:snapshot,index:0,round:1,phase:'exercise',seconds:0,paused:false,session:workoutSession(snapshot.id,{date:dateKey(today),name:snapshot.name})};view='session';startExercise();}
function startExercise(){let item=active.workout.exercises[active.index];if(item?.durationSeconds){active.seconds=item.durationSeconds;timer=new CountdownTimer(n=>{active.seconds=n;document.querySelector('#clock')&&(document.querySelector('#clock').textContent=formatSeconds(n));},()=>advance());timer.start(active.seconds);}render();}
function advance(){timer?.stop();let w=active.workout;if(active.index<w.exercises.length-1){active.index++;return startRest(w.defaultRestSeconds??w.restBetweenExercises??state.preferences.restBetweenExercises);}if(active.round<w.rounds){active.round++;active.index=0;return startRest(w.restBetweenRounds??state.preferences.restBetweenRounds);}finish();}
function startRest(seconds){active.phase='rest';active.seconds=seconds;timer=new CountdownTimer(n=>{active.seconds=n;document.querySelector('#clock')&&(document.querySelector('#clock').textContent=formatSeconds(n));},()=>{active.phase='exercise';startExercise();});timer.start(seconds);render();}
function finish(){timer?.stop();active.session.completedAt=new Date().toISOString();active.session.durationSeconds=Math.round((Date.now()-new Date(active.session.startedAt))/1000);state=addSession(state,active.session);persist();active=null;view='home';render();}
async function act(action){if(action==='start')return begin();if(action==='goto-editor'){view='editor';return render();}if(action==='start-mobility'){const mobility=mobilityWorkout();if(mobility)begin(mobility);return;}if(action==='complete-activity')return finish();if(action==='complete-exercise'){let item=active.workout.exercises[active.index];active.session.completedExercises.push(exerciseSession(item.exerciseId,{completed:true,repetitions:item.repetitions,duration:item.durationSeconds||0}));return advance();}if(action==='skip')return advance();if(action==='repeat'){timer?.stop();return startExercise();}if(action==='skip-rest'){timer?.stop();active.phase='exercise';return startExercise();}if(action==='pause'){timer?.pause();active.paused=true;return render();}if(action==='resume'){timer?.resume();active.paused=false;return render();}if(action==='exit'){if(confirm('¿Salir y perder esta sesión?')){timer?.stop();active=null;view='home';render();}return;}if(action==='save-settings'){let p=state.preferences;p.reminders.enabled=document.querySelector('#reminder').checked;p.reminders.time=document.querySelector('#time').value;p.restBetweenExercises=+document.querySelector('#rest-ex').value;p.restBetweenRounds=+document.querySelector('#rest-round').value;p.stretchSeconds=+document.querySelector('#stretch').value;p.theme=document.querySelector('#theme').value;if(p.reminders.enabled&&!await requestReminderPermission())alert('No se concedió permiso para notificaciones.');persist();return render();}if(action==='export'){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([exportHistory(state.sessions)],{type:'application/json'}));a.download='entrena-historial.json';a.click();}if(action==='clear'){if(confirm('¿Borrar todo el historial?')){state=clearHistory(state);persist();render();}}if(action==='about')alert('Ejercicios dataset\nLa atribución se genera en public/exercises/ATTRIBUTION.md al importar recursos verificados.');}
function applyTheme(){document.documentElement.dataset.theme=state.preferences.theme;}
if('serviceWorker'in navigator)navigator.serviceWorker.register('/service-worker.js');applyTheme();persist();render();
