import { weeklyWorkouts, workoutForDate, nextWorkoutForDate, weeklyProgress, getExercise, dateKey, mobility } from './routines.js';
import { loadState, saveState, addSession, clearHistory, statistics, exportHistory } from './storage.js';
import { workoutSession, exerciseSession } from './models.js';
import { CountdownTimer, formatSeconds } from './timer.js';
import { requestReminderPermission, scheduleBrowserReminder } from './notifications.js';

let state=loadState(localStorage), view='home', active=null, timer; const app=document.querySelector('#app'),tabs=document.querySelector('#tabs');
const today=new Date(), dayFmt=new Intl.DateTimeFormat('es-ES',{weekday:'long',day:'numeric',month:'long'}), icon={fuerza:'🏋',running:'🏃',piscina:'🏊',movilidad:'🧘'};
const persist=()=>{saveState(localStorage,state);applyTheme();scheduleBrowserReminder(state.preferences,workoutForDate(today));};
const completedToday=()=>state.sessions.some(s=>s.date===dateKey(today)&&s.completedAt);
const button=(text,action,secondary=false)=>`<button class="${secondary?'secondary':''}" data-action="${action}">${text}</button>`;
function shell(content){app.innerHTML=content;tabs.innerHTML=['home:Hoy','calendar:Semana','history:Historial','settings:Ajustes'].map(x=>{let[a,b]=x.split(':');return `<button class="${view===a?'selected':''}" data-view="${a}">${b}</button>`}).join('');document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{view=b.dataset.view;render();});document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>act(b.dataset.action));}
function home(){const w=workoutForDate(today),next=nextWorkoutForDate(today),p=weeklyProgress(state.sessions,today),done=completedToday();shell(`<header><p class="eyebrow">HOY</p><h1>${dayFmt.format(today)}</h1></header><section class="hero"><span>${icon[w.type]}</span><p class="eyebrow">${w.type.toUpperCase()}</p><h2>${w.name}</h2><p>${w.isActivity?w.description:`${w.exercises.length} ejercicios · ${w.rounds} rondas`}</p>${done?'<div class="complete">✓ Entrenamiento completado</div>':button('Comenzar entrenamiento','start')}</section><section><p class="eyebrow">MOVILIDAD</p><h2>Mobility & Stretching</h2><p>Sesión guiada de 10 ejercicios.</p>${button('Iniciar movilidad','start-mobility',true)}</section><section><p class="eyebrow">PRÓXIMO ENTRENAMIENTO</p><h2>${next.name}</h2><p>${icon[next.type]} Mañana · ${next.type}</p></section><section><p class="eyebrow">PROGRESO</p><h2>Esta semana <strong>${p.completed}/5</strong></h2><div class="bar"><i style="width:${p.completed/5*100}%"></i></div></section>`);}
function calendar(){shell(`<header><p class="eyebrow">CALENDARIO</p><h1>Esta semana</h1></header><section class="week">${weeklyWorkouts.map((w,i)=>{let d=new Date(today);d.setDate(today.getDate()-((today.getDay()+6)%7)+i);let done=state.sessions.some(s=>s.date===dateKey(d)&&s.completedAt);return `<button data-day="${i}" class="day ${dateKey(d)===dateKey(today)?'today':''}"><b>${'LMXJVSD'[i]}</b><span>${icon[w.type]}</span><small>${w.name}</small><em>${done?'✓':'○'}</em></button>`}).join('')}</section><section><h2>Plan de hoy</h2><p>${workoutForDate(today).description||'Rutina guiada con descansos automáticos.'}</p></section>`);document.querySelectorAll('[data-day]').forEach(b=>b.onclick=()=>alert(`${weeklyWorkouts[+b.dataset.day].name}\n${weeklyWorkouts[+b.dataset.day].description||'Rutina de 3 rondas.'}`));}
function history(){const sessions=[...state.sessions].filter(s=>s.completedAt).sort((a,b)=>b.completedAt.localeCompare(a.completedAt));const stat=statistics(state.sessions,today);shell(`<header><p class="eyebrow">HISTORIAL</p><h1>Tu progreso</h1></header><section class="stats"><div><b>${stat.completed}</b><span>completados</span></div><div><b>${stat.week}</b><span>esta semana</span></div><div><b>${stat.streak}</b><span>días seguidos</span></div></section><section><h2>Sesiones</h2>${sessions.length?sessions.map(s=>`<button class="history" data-session="${s.id}"><span>${new Intl.DateTimeFormat('es-ES',{day:'numeric',month:'short'}).format(new Date(s.completedAt))}</span><b>${s.name}</b><em>✓</em></button>`).join(''):'<p>Aún no has completado entrenamientos.</p>'}</section>`);document.querySelectorAll('[data-session]').forEach(b=>b.onclick=()=>{let s=sessions.find(x=>x.id===b.dataset.session);alert(`${s.name}\nDuración: ${Math.round(s.durationSeconds/60)} min\nEjercicios completados: ${s.completedExercises.length}`);});}
function settings(){let p=state.preferences; shell(`<header><p class="eyebrow">AJUSTES</p><h1>Personaliza</h1></header><section><h2>Recordatorios</h2><label class="toggle">Activar <input id="reminder" type="checkbox" ${p.reminders.enabled?'checked':''}></label><label>Hora <input id="time" type="time" value="${p.reminders.time}"></label><small>En web, el recordatorio funciona mientras esta app permanece abierta.</small></section><section><h2>Entrenamiento</h2><label>Descanso entre ejercicios <input id="rest-ex" type="number" min="0" value="${p.restBetweenExercises}"> segundos</label><label>Descanso entre rondas <input id="rest-round" type="number" min="0" value="${p.restBetweenRounds}"> segundos</label><label>Estiramientos <input id="stretch" type="number" min="5" value="${p.stretchSeconds}"> segundos</label></section><section><h2>Apariencia</h2><select id="theme"><option value="system">Sistema</option><option value="light">Claro</option><option value="dark">Oscuro</option></select></section><section><h2>Datos</h2>${button('Guardar ajustes','save-settings')}${button('Exportar historial','export',true)}${button('Borrar historial','clear',true)}${button('Acerca de / licencias','about',true)}</section>`);document.querySelector('#theme').value=p.theme;}
function sessionView(){let {workout,index,round,phase,session}=active, item=workout.exercises[index], ex=item&&getExercise(item.exerciseId), rest=phase==='rest';shell(`<header><button class="back" data-action="exit">× Salir</button><p class="eyebrow">${rest?'DESCANSO':workout.isActivity?'ACTIVIDAD':`RONDA ${round} / ${workout.rounds}`}</p></header><section class="session">${rest?`<h1>Descanso</h1><div id="clock" class="clock">${formatSeconds(active.seconds)}</div><p>Siguiente: <b>${getExercise(workout.exercises[index].exerciseId).displayName}</b></p>${button('Omitir descanso','skip-rest',true)}`:workout.isActivity?`<span class="activity-icon">${icon[workout.type]}</span><h1>${workout.name}</h1><p>${workout.description}</p>${button('Marcar como completado','complete-activity')}`:`<h1>${ex.displayName}</h1><div class="media">GIF disponible tras importar el dataset</div><h2>${item.repetitions||`${item.durationSeconds} segundos`}</h2>${item.notes?`<p>${item.notes}</p>`:''}${item.durationSeconds?`<div id="clock" class="clock">${formatSeconds(active.seconds)}</div>${button(active.paused?'Reanudar':'Pausar',active.paused?'resume':'pause',true)}`:''}${button('✓ Completar','complete-exercise')}${button('Repetir ejercicio','repeat',true)}${button('Saltar ejercicio','skip',true)}`}</section>`);}
function render(){if(view==='home')home();else if(view==='calendar')calendar();else if(view==='history')history();else if(view==='settings')settings();else sessionView();}
function begin(workout=workoutForDate(today)){active={workout,index:0,round:1,phase:'exercise',seconds:0,paused:false,session:workoutSession(workout.id,{date:dateKey(today),name:workout.name})};view='session';startExercise();}
function startExercise(){let item=active.workout.exercises[active.index];if(item?.durationSeconds){active.seconds=item.durationSeconds;timer=new CountdownTimer(n=>{active.seconds=n;document.querySelector('#clock')&&(document.querySelector('#clock').textContent=formatSeconds(n));},()=>advance());timer.start(active.seconds);}render();}
function advance(){timer?.stop();let w=active.workout;if(active.index<w.exercises.length-1){active.index++;return startRest(w.restBetweenExercises??state.preferences.restBetweenExercises);}if(active.round<w.rounds){active.round++;active.index=0;return startRest(w.restBetweenRounds??state.preferences.restBetweenRounds);}finish();}
function startRest(seconds){active.phase='rest';active.seconds=seconds;timer=new CountdownTimer(n=>{active.seconds=n;document.querySelector('#clock')&&(document.querySelector('#clock').textContent=formatSeconds(n));},()=>{active.phase='exercise';startExercise();});timer.start(seconds);render();}
function finish(){timer?.stop();active.session.completedAt=new Date().toISOString();active.session.durationSeconds=Math.round((Date.now()-new Date(active.session.startedAt))/1000);state=addSession(state,active.session);persist();active=null;view='home';render();}
async function act(action){if(action==='start')return begin();if(action==='start-mobility')return begin(mobility);if(action==='complete-activity')return finish();if(action==='complete-exercise'){let item=active.workout.exercises[active.index];active.session.completedExercises.push(exerciseSession(item.exerciseId,{completed:true,repetitions:item.repetitions,duration:item.durationSeconds||0}));return advance();}if(action==='skip')return advance();if(action==='repeat'){timer?.stop();return startExercise();}if(action==='skip-rest'){timer?.stop();active.phase='exercise';return startExercise();}if(action==='pause'){timer?.pause();active.paused=true;return render();}if(action==='resume'){timer?.resume();active.paused=false;return render();}if(action==='exit'){if(confirm('¿Salir y perder esta sesión?')){timer?.stop();active=null;view='home';render();}return;}if(action==='save-settings'){let p=state.preferences;p.reminders.enabled=document.querySelector('#reminder').checked;p.reminders.time=document.querySelector('#time').value;p.restBetweenExercises=+document.querySelector('#rest-ex').value;p.restBetweenRounds=+document.querySelector('#rest-round').value;p.stretchSeconds=+document.querySelector('#stretch').value;p.theme=document.querySelector('#theme').value;if(p.reminders.enabled&&!await requestReminderPermission())alert('No se concedió permiso para notificaciones.');persist();return render();}if(action==='export'){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([exportHistory(state.sessions)],{type:'application/json'}));a.download='entrena-historial.json';a.click();}if(action==='clear'){if(confirm('¿Borrar todo el historial?')){state=clearHistory(state);persist();render();}}if(action==='about')alert('Ejercicios dataset\nLa atribución se genera en public/exercises/ATTRIBUTION.md al importar recursos verificados.');}
function applyTheme(){document.documentElement.dataset.theme=state.preferences.theme;}
if('serviceWorker'in navigator)navigator.serviceWorker.register('/service-worker.js');applyTheme();persist();render();
